CREATE TABLE `T_MEMBER` (
  `ID` varchar(50) NOT NULL COMMENT '아이디',
  `PW` varchar(50) NOT NULL COMMENT '패스워드',
  `NAME` varchar(40) NOT NULL COMMENT '이름',
  `NICKNAME` varchar(30) NOT NULL COMMENT '별명',
  `BIRTHDATE` datetime DEFAULT NULL COMMENT '생년월일',
  `GENDER` char(1) DEFAULT NULL COMMENT '성별',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='회원정보'

CREATE TABLE `T_PERFUME` (
  `P_NUM` int unsigned NOT NULL AUTO_INCREMENT COMMENT '향수번호',
  `P_BRAND` varchar(50) NOT NULL COMMENT '브랜드명',
  `P_MODEL` varchar(50) NOT NULL COMMENT '모델명',
  `P_TOP` varchar(50) NOT NULL COMMENT '탑노트',
  `P_MIDDLE` varchar(50) NOT NULL COMMENT '미들노트',
  `P_BASE` varchar(50) NOT NULL COMMENT '베이스노트',
  `P_MOOD` varchar(500) NOT NULL COMMENT '분위기',
  `P_PICPATH` varchar(1000) NOT NULL COMMENT '사진주소',
  `P_INFO` text NOT NULL COMMENT '향수설명',
  `P_PATH` varchar(1000) DEFAULT NULL COMMENT '향수주소',
  PRIMARY KEY (`P_NUM`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='향수정보'


CREATE TABLE `T_LOG` (
  `LOG_NUM` int unsigned NOT NULL AUTO_INCREMENT COMMENT '로그번호',
  `ID` varchar(50) NOT NULL COMMENT '회원아이디',
  `M_NUM` int unsigned NOT NULL COMMENT '음악번호',
  `P_NUM` int unsigned NOT NULL COMMENT '향수번호',
  `LOG_STF` char(1) NOT NULL COMMENT '만족도',
  PRIMARY KEY (`LOG_NUM`),
  KEY `P_NUM` (`P_NUM`),
  KEY `M_NUM` (`M_NUM`),
  KEY `FK_T_MEMBER_ID_T_LOG_ID` (`ID`),
  CONSTRAINT `FK_T_MEMBER_ID_T_LOG_ID` FOREIGN KEY (`ID`) REFERENCES `T_MEMBER` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `T_LOG_ibfk_1` FOREIGN KEY (`P_NUM`) REFERENCES `T_PERFUME` (`P_NUM`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `T_LOG_ibfk_2` FOREIGN KEY (`M_NUM`) REFERENCES `T_MUSIC` (`M_NUM`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='로그정보'